services:
  auth-service:
    build: ./auth-service

    container_name: auth-service
    ports: 
      - "3003:3003"
    env_file: .env
    depends_on:
      user-db:
        condition: service_started
    command: >
      sh -c "node app.js"

  user-service:
    build: ./user-service
    
    container_name: user-service
    ports:
      - "3005:3005"
    env_file: .env
    depends_on:
      user-db:
        condition: service_healthy
    command: >
      sh -c "npx knex migrate:latest && node app.js"

  dokter-service:
    build: ./dokter-service
    container_name: dokter-service
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      doctor-db:
        condition: service_healthy
    command: >
      sh -c "npx knex migrate:latest && node app.js"

  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      booking-db:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    restart: always
    ports:
      - "3004:3004"
    env_file:
      - ./notification-service/.env

  user-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    ports:
      - "5435:5432"
    volumes:
      - user_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

  booking-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${BOOKING_DB_USER}
      POSTGRES_PASSWORD: ${BOOKING_DB_PASSWORD}
      POSTGRES_DB: ${BOOKING_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - clinic_booking:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ${BOOKING_DB_USER} -d ${BOOKING_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  doctor-db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - clinic:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  user_db:
  clinic_booking:
  clinic:
